quizapp/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.AccountLoginView.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/accounts/login'}, name='logout'),
    url(r'^register/$', views.AccountRegisterView.as_view(), name='register'),
    url(r'^dashboard/$', views.AccountDashboardView.as_view(), name='dashboard')
]

quizapp/quizapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('takes.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('quizzes.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

quizapp/quizzes/urls.py
from django.conf.urls import url

from . import views

app_name = 'quizzes'
urlpatterns = [
    url(r'^$', views.QuizIndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.QuizDetailView.as_view(), name='detail'),
    url(
        r'^(?P<pk>[0-9]+)/quiz/(?P<take>[0-9]+)$',
        views.QuestionQuizView.as_view(),
        name='quiz'
    ),
    url(r'^quiz/create/$', views.QuizCreateView.as_view(), name='create'),
    url(
        r'^quiz/usercreated/$',
        views.QuizCreatedListView.as_view(),
        name='usercreated'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/update$',
        views.QuizUpdateView.as_view(),
        name='quiz_update'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/delete$',
        views.QuizDeleteView.as_view(),
        name='quiz_delete'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/$',
        views.QuizCreatedDetailView.as_view(),
        name='usercreated_detail'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/createquestion/$',
        views.QuestionCreateView.as_view(),
        name='question_create'
    ),
    url(
        r'^quiz/usercreated/(?P<question_id>[0-9]+)/updatequestion/',
        views.QuestionUpdateView.as_view(),
        name='question_update'
    ),
    url(
        r'^quiz/usercreated/(?P<question_id>[0-9]+)/deletequestion/',
        views.QuestionDeleteView.as_view(),
        name='question_delete'
    ),
    url(
        r'^quiz/usercreated/(?P<question_id>[0-9]+)/createchoice/$',
        views.ChoiceCreateView.as_view(),
        name='choice_create'
    ),
    url(
        r'^quiz/usercreated/(?P<choice_id>[0-9]+)/updatechoice/$',
        views.ChoiceUpdateView.as_view(),
        name='choice_update'
    ),
    url(
        r'^quiz/usercreated/(?P<choice_id>[0-9]+)/deletechoice/$',
        views.ChoiceDeleteView.as_view(),
        name='choice_delete'
    )
]

quizapp/takes/urls.py
from django.conf.urls import url

from . import views

app_name = 'takes'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results')
]

quizapp/accounts/models.py
from django.db import models

# Create your models here.

quizapp/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Enter username',
            'class': 'form-control'
        }))
        password = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Enter password',
            'class': 'form-control',
            'type': 'password'
        }))


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

quizapp/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, View

from takes.models import Take

from .forms import LoginForm, RegistrationForm


# Create your views here.
class AccountLoginView(View):
    def get(self, request):
        form = LoginForm()
        args = {'form': form}
        return render(request, 'accounts/login.html', args)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('quizzes:index'))

        messages.add_message(
            request, 50, 'Wrong login credentials.', extra_tags='danger'
        )
        return render(request, 'accounts/login.html', {'form': form})


class AccountRegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/register.html', args)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Successfully Registered. You can now login.'
             )
            return HttpResponseRedirect(reverse('accounts:login'))
        return render(request, 'accounts/register.html', {'form': form})


class AccountDashboardView(LoginRequiredMixin, ListView):
    model = Take
    paginate_by = 10
    template_name = 'accounts/dashboard.html'
    context_object_name = 'takes'

    def get_queryset(self):
        return Take.objects.filter(
            user__exact=self.request.user
        ).order_by('-date_taken')

    def handle_no_permission(self):
        messages.warning(
            self.request, 'You must login first to view dashboard'
        )
        return super(AccountDashboardView, self).handle_no_permission()

quizapp/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1 class="text-center">Recent Quizzes Taken</h1>
    {% if messages %}
        {% for message in messages %}
            <p class="text-center text-danger"> {{ message }}</p>
        {% endfor %}
    {% endif %}

    {% if takes %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Quiz Name</th>
                <th scope="col">Date Taken</th>
                <th score="col">Score</th>
            </tr>
        </thead>
        <tbody>
            {% for take in takes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'takes:results' take.id %}">{{ take.quiz }}</a></td>
                <td>{{ take.date_taken }}</td>
                <td>{{ take.score }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h4 class="text-center">No quiz taken yet. <a href="{% url 'quizzes:index' %}">Take a quiz now</a></h4>
    {% endif %}
</div>

{% include 'pagination.html' %}

{% endblock %}

quizapp/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1 class="text-center">Login</h1>
    <p class="text-center">
        {% if error_message %}
        <small class="text-danger">{{ error_message }}</small>
        {% endif %}
    </p>
    <p class="text-center">
        {% if messages %}
            {% for message in messages %}
            <small{% if message.tags %} class="text-{{ message.tags }}"{% endif %}>{{ message }}</small>
            {% endfor %}
        {% endif %}
    </p>
    <p class="text-center">
        <small>Not yet registered? <a href="{% url 'accounts:register' %}">Register here</a></small>
    </p>

    <form class="col-md-4 offset-md-4" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <small class="text-danger">{{ field.errors }}</small>
                <label>{{ field.label_tag}}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-block btn-primary">Login</button>
    </form>
    <div class="col-md-4 offset-md-4 text-center">
        <hr>
        <p>Login via Social</p>
        <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-outline-primary">
            <span class="fab fa-google"></span>
        </a>
        <a href="{% url 'social:begin' 'github' %}" class="btn btn-outline-primary">
            <span class="fab fa-github"></span>
        </a>
        <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-outline-primary">
            <span class="fab fa-facebook"></span>
        </a>
        <br>
    </div>
</div>
{% endblock %}

quizapp/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1 class="text-center">Register</h1>
    <form class="col-md-4 offset-md-4" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <small class="text-danger">{{ field.errors }}</small>
                <label>{{ field.label_tag}}</label>
                {{ field }}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-block btn-primary" value="Register">
    </form>
    <div class="col-md-4 offset-md-4 text-center">
        <hr>
        <p>Register via Social</p>
        <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-outline-primary">
            <span class="fab fa-google"></span>
        </a>
        <a href="{% url 'social:begin' 'github' %}" class="btn btn-outline-primary">
            <span class="fab fa-github"></span>
        </a>
        <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-outline-primary">
            <span class="fab fa-facebook"></span>
        </a>
        <br>

    </div>
</div>
{% endblock %}