quizapp/quizapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('takes.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('quizzes.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

quizapp/quizzes/urls.py
from django.conf.urls import url

from . import views

app_name = 'quizzes'
urlpatterns = [
    url(r'^$', views.QuizIndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.QuizDetailView.as_view(), name='detail'),
    url(
        r'^(?P<pk>[0-9]+)/quiz/(?P<take>[0-9]+)$',
        views.QuestionQuizView.as_view(),
        name='quiz'
    ),
    url(r'^quiz/create/$', views.QuizCreateView.as_view(), name='create'),
    url(
        r'^quiz/usercreated/$',
        views.QuizCreatedListView.as_view(),
        name='usercreated'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/update$',
        views.QuizUpdateView.as_view(),
        name='quiz_update'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/delete$',
        views.QuizDeleteView.as_view(),
        name='quiz_delete'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/$',
        views.QuizCreatedDetailView.as_view(),
        name='usercreated_detail'
    ),
    url(
        r'^quiz/usercreated/(?P<pk>[0-9]+)/createquestion/$',
        views.QuestionCreateView.as_view(),
        name='question_create'
    ),
    url(
        r'^quiz/usercreated/(?P<question_id>[0-9]+)/updatequestion/',
        views.QuestionUpdateView.as_view(),
        name='question_update'
    ),
    url(
        r'^quiz/usercreated/(?P<question_id>[0-9]+)/deletequestion/',
        views.QuestionDeleteView.as_view(),
        name='question_delete'
    ),
    url(
        r'^quiz/usercreated/(?P<question_id>[0-9]+)/createchoice/$',
        views.ChoiceCreateView.as_view(),
        name='choice_create'
    ),
    url(
        r'^quiz/usercreated/(?P<choice_id>[0-9]+)/updatechoice/$',
        views.ChoiceUpdateView.as_view(),
        name='choice_update'
    ),
    url(
        r'^quiz/usercreated/(?P<choice_id>[0-9]+)/deletechoice/$',
        views.ChoiceDeleteView.as_view(),
        name='choice_delete'
    )
]

quizapp/takes/urls.py
from django.conf.urls import url

from . import views

app_name = 'takes'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results')
]

quizapp/quizzes/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
def timezone_now_plus_one_day():
    return timezone.now() + datetime.timedelta(days=1)


class Quiz(models.Model):
    title = models.CharField(max_length=200)
    date_created = models.DateTimeField(default=timezone.now)
    expiration_date = models.DateTimeField(default=timezone_now_plus_one_day)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    published = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "quizzes"

    def __str__(self):
        return self.title


class Question(models.Model):
    question_text = models.CharField(max_length=256)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=256)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

quizapp/quizzes/forms.py
from django import forms
from django.forms import ModelForm

from .models import Choice, Question, Quiz


class QuizCreateForm(ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter quiz title',
        'class': 'form-control'
    }))
    expiration_date = forms.DateTimeField(
        widget=forms.SelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day"),
        ),
    )

    class Meta:
        model = Quiz
        fields = ['title', 'expiration_date', 'published']


class QuestionCreateForm(ModelForm):
    question_text = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter question',
        'class': 'form-control'
    }))

    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceCreateForm(ModelForm):
    choice_text = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter choice',
        'class': 'form-control'
    }))
    is_correct = forms.BooleanField(initial=False, required=False)

    class Meta:
        model = Choice
        fields = ['choice_text', 'is_correct']

quizapp/quizzes/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.forms.models import model_to_dict
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import DetailView, ListView, View

from takes.models import Answer, Take

from .forms import ChoiceCreateForm, QuestionCreateForm, QuizCreateForm
from .models import Choice, Question, Quiz


# Create your views here.
class QuizIndexView(ListView):
    model = Quiz
    template_name = 'quizzes/index.html'
    context_object_name = 'quiz_list'
    paginate_by = 20

    def get_queryset(self):
        return Quiz.objects.filter(
            date_created__lte=timezone.now(),
            expiration_date__gte=timezone.now(),
            published__exact=True
        ).order_by('-date_created')


class QuizDetailView(DetailView):
    model = Quiz
    template_name = 'quizzes/detail.html'

    def get_queryset(self):
        return Quiz.objects.filter(expiration_date__gte=timezone.now())

    def post(self, request, pk):
        if not request.user.is_authenticated():
            messages.warning(
                self.request, 'You must be logged in to take a quiz'
            )
            return HttpResponseRedirect(reverse('accounts:login'))
        user = request.user
        quiz = get_object_or_404(Quiz, pk=pk)
        take = Take.objects.create(user=user, quiz=quiz)
        return HttpResponseRedirect(reverse('quizzes:quiz', kwargs={
            'pk': quiz.id,
            'take': take.id
        }))


class QuestionQuizView(LoginRequiredMixin, View):
    def get(self, request, pk, take):
        take = get_object_or_404(Take, pk=take)
        question_list = get_object_or_404(Quiz, pk=pk).question_set.all()
        paginator = Paginator(question_list, 1)
        if (request.user != take.user or question_list.count() == 0 or not
                take.quiz.published):
            messages.add_message(
                request, messages.INFO, 'You are not allowed to view the quiz'
            )
            return HttpResponseRedirect(reverse('accounts:dashboard'))

        page = request.GET.get('question')
        try:
            questions = paginator.page(page)
        except PageNotAnInteger:
            questions = paginator.page(1)
        except EmptyPage:
            questions = paginator.page(paginator.num_pages)
        return render(request, 'quizzes/quiz.html', {'questions': questions})

    def post(self, request, pk, take):
        next = request.POST.get('next', '/')
        if request.GET.get('question'):
            next = next + "?question=" + request.GET.get('question')
        try:
            choice = get_object_or_404(Choice, pk=request.POST['answer'])
            session = get_object_or_404(Take, pk=take)
            question = choice.question
            Answer.objects.create(
                selected_choice=choice,
                question=question,
                take=session
            )
            if request.POST.get('finish'):
                return HttpResponseRedirect(reverse('accounts:dashboard'))
        except MultiValueDictKeyError:
            return HttpResponseRedirect(next)

    def handle_no_permission(self):
        messages.warning(
            self.request, 'You are not allowed to view this page.'
        )
        return super(QuestionQuizView, self).handle_no_permission()


class QuizCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = QuizCreateForm()
        return render(
            request, 'quizzes/quiz_create.html',
            {'form': form, 'action': 'Create'}
        )

    def post(self, request):
        form = QuizCreateForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            expiration_date = datetime.datetime(
                int(request.POST.get('expiration_date_year')),
                int(request.POST.get('expiration_date_month')),
                int(request.POST.get('expiration_date_day')),
            )
            quiz.expiration_date = expiration_date
            quiz.created_by = request.user
            quiz.save()
        return HttpResponseRedirect(reverse('quizzes:index'))


class QuizUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        quiz = get_object_or_404(Quiz, pk=pk)
        if quiz.created_by != request.user:
            messages.add(
                request, messages.INFO, 'You are not allowed to view the quiz'
            )
            return HttpResponseRedirect(reverse('quizzes:usercreated'))
        form = QuizCreateForm(model_to_dict(quiz))
        return render(
            request, 'quizzes/quiz_create.html',
            {'form': form, 'action': 'Update', 'quiz': quiz}
         )

    def post(self, request, pk):
        form = QuizCreateForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            expiration_date = datetime.datetime(
                int(request.POST.get('expiration_date_year')),
                int(request.POST.get('expiration_date_month')),
                int(request.POST.get('expiration_date_day')),
            )
            quiz.id = pk
            quiz.expiration_date = expiration_date
            quiz.created_by = request.user
            quiz.save()
        return HttpResponseRedirect(reverse('quizzes:usercreated'))


class QuizDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        quiz = get_object_or_404(Quiz, pk=pk)
        if quiz.created_by != request.user:
            messages.add(
                request, messages.INFO, 'You are not allowed to view the quiz'
            )
            return HttpResponseRedirect(reverse('quizzes:usercreated'))
        quiz.delete()
        return HttpResponseRedirect(reverse('quizzes:usercreated'))


class QuizCreatedListView(LoginRequiredMixin, ListView):
    model = Quiz
    template_name = "quizzes/quiz_created_index.html"

    def get_queryset(self):
        return Quiz.objects.filter(
            created_by__exact=self.request.user
        ).order_by('-date_created')


class QuizCreatedDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        quiz = get_object_or_404(Quiz, pk=pk)
        return render(
            request, 'quizzes/quiz_created_detail.html',
            {'quiz': quiz}
        )


class QuestionCreateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        quiz = get_object_or_404(Quiz, pk=pk)
        form = QuestionCreateForm()
        return render(
            request, 'quizzes/question_create.html',
            {'quiz': quiz, 'form': form, 'action': 'Add'}
        )

    def post(self, request, pk):
        form = QuestionCreateForm(request.POST)
        question = form.save(commit=False)
        question.quiz = get_object_or_404(Quiz, pk=pk)
        question.save()
        return HttpResponseRedirect(
            reverse('quizzes:usercreated_detail', kwargs={
                'pk': pk
            })
        )


class QuestionUpdateView(LoginRequiredMixin, View):
    def get(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        if request.user != question.quiz.created_by:
            messages.add(
                request, messages.INFO, 'You are not allowed to view the quiz'
            )
            return HttpResponseRedirect(
                reverse(
                    'quizzes:usercreated_detail',
                    kwargs={'pk': question.quiz.id}
                )
            )
        form = QuestionCreateForm(model_to_dict(question))
        return render(
            request, 'quizzes/question_create.html',
            {'form': form, 'action': 'Update', 'question_id': question.id}
        )

    def post(self, request, question_id):
        form = QuestionCreateForm(request.POST)
        if form.is_valid():
            question_object = get_object_or_404(Question, pk=question_id)
            question = form.save(commit=False)
            question.id = question_object.id
            question.quiz = question_object.quiz
            question.save()

        return HttpResponseRedirect(
            reverse('quizzes:usercreated_detail', kwargs={
                'pk': question.quiz.id,
            })
        )


class QuestionDeleteView(LoginRequiredMixin, View):
    def get(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        if question.quiz.created_by != request.user:
            messages.add(
                request, messages.INFO, 'You are not allowed to view the quiz'
            )
            return HttpResponseRedirect(reverse('quizzes:usercreated'))
        question.delete()
        return HttpResponseRedirect(reverse(
            'quizzes:usercreated_detail', kwargs={'pk': question.quiz.id}
            ))


class ChoiceCreateView(LoginRequiredMixin, View):
    def get(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        form = ChoiceCreateForm()
        return render(
            request, 'quizzes/choice_create.html',
            {'question': question, 'form': form, 'action': 'Add'}
        )

    def post(self, request, question_id):
        form = ChoiceCreateForm(request.POST)
        choice = form.save(commit=False)
        choice.question = get_object_or_404(Question, pk=question_id)
        choice.save()
        return HttpResponseRedirect(
            reverse('quizzes:usercreated_detail', kwargs={
                'pk': choice.question.quiz.id
            })
        )


class ChoiceUpdateView(LoginRequiredMixin, View):
    def get(self, request, choice_id):

quizapp/quizzes/templates/quizzes/choice_create.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-center">Create a Choice</h1>
<h3 class="text-center">Question: {{ question }}</h3>
<hr>

<div class="col-md-4 offset-md-4 text-center">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {% if choice_id %}
        <a href="{% url 'quizzes:choice_delete' choice_id%}" class="btn btn-danger col-md-5">Delete</a>
        <button class="btn btn-success col-md-5 offset-md-1">{{ action }} Choice</button>
        {% else %}
        <button class="btn btn-success btn-block">{{ action }} Choice</button>
        {% endif %}
    </form>
</div>


{% endblock %}

quizapp/quizzes/templates/quizzes/detail.html
{% extends 'base.html' %}
{% load question_extras %}

{% block head %}
<title>Quiz Application | Home</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">Quiz: {{ quiz.title }}</h1>
    <hr>
    {% if quiz|has_questions %}
    <p class='text-center'>Number of questions: {{ quiz.question_set.count }}</p>
    <form method="POST">
        {% csrf_token %}
        <button class="align-center btn btn-primary btn-lg offset-md-4 col-md-4" type="submit">Start Quiz</button>
    </form>
    {% else %}
    <p class="text-center">Quiz has not yet been setup. No questions available.</p>
    {% endif %}
</div>

{% endblock %}

quizapp/quizzes/templates/quizzes/index.html
{% extends 'base.html' %}

{% block head %}
<title>Quiz Application | Home</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">List of Quizzes</h1>
    <hr> {% if quiz_list %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Quiz Name</th>
                <th scope="col">Created by</th>
                <th scope="col">Date Created</th>
                <th scope="col">Expiration Date</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in quiz_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'quizzes:detail' quiz.id %}">{{ quiz.title }}</a></td>
                <td>{{ quiz.created_by }}</td>
                <td>{{ quiz.date_created|date:'F d, Y' }}</td>
                <td>{{ quiz.expiration_date|date:'F d, Y' }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h4 class="text-center">No quizzes available today</h4> {% endif %} {% include 'pagination.html' %}
</div>
{% endblock %}

quizapp/quizzes/templates/quizzes/question_create.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-center">Create a Question</h1>
<h3 class="text-center">Quiz: {{ quiz.title }}</h3>
<hr>

<div class="col-md-4 offset-md-4 text-center">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {% if question_id %}
        <a href="{% url 'quizzes:question_delete' question_id%}" class="btn btn-danger col-md-5">Delete</a>
        <button class="btn btn-success col-md-5 offset-md-1">{{ action }} Question</button>
        {% else %}
        <button class="btn btn-success btn-block">{{ action }} Question</button>
        {% endif %}
    </form>
</div>


{% endblock %}

quizapp/quizzes/templates/quizzes/quiz.html
{% extends 'base.html' %}

{% block head %}
<title>Quiz Application | Home</title>
{% endblock %}

{% block body %}
<div class="container">
    {% with questions|first as question %}
    <h1 class="text-center"> {{ question.quiz }}</h1> {% endwith %}
    <hr> {% for question in questions %}
    <p class="text-center">{{ question }}</p>
    <div class="pagination col-md-4 offset-md-4">
        <span class="mx-auto">
                {% if questions.has_previous %}
                <a href="?question={{ questions.previous_page_number }}">&lt&lt </a>
                {% endif %}
                <span class="current">
                    Question {{ questions.number }} of {{ questions.paginator.num_pages }}
                </span> {% if questions.has_next %}
        <a href="?question={{ questions.next_page_number }}"> &gt&gt</a> {% endif %}
        </span>
    </div>
    <form method=post>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <div class="col-md-4 offset-md-4 text-center">
            <hr>
            <table>
                <tr>
                    {% for choice in question.choice_set.all %} {% if messages %} {% for message in messages %}
                    <small class="text-success">{{ message }}</small> {% endfor %} {% endif %}
                    <td>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ choice.id }}" class="custom-control-input">
                            <label for="answer{{ forloop.counter }}" class="custom-control-label">{{ choice }}</label>
                        </div>
                    </td>
                    {% endfor %}
                </tr>
            </table>
            <hr>
        </div>
        <div class="col-md-4 offset-md-4 text-center">
            {% if questions.number == questions.paginator.num_pages %}
            <input type="hidden" name="finish" value="1">
            <button class="btn btn-xs btn-success text-center" type="submit">End Quiz</button> {% else %}
            <button class="btn btn-xs btn-success text-center" type="submit">Submit answer</button> {% endif %}
        </div>
    </form>
    {% endfor %}
</div>
{% endblock %}

quizapp/quizzes/templates/quizzes/quiz_create.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-center">Create a Quiz</h1>
<hr>

<div class="col-md-4 offset-md-4 text-center">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {% if quiz.id %}
        <a href="{% url 'quizzes:quiz_delete' quiz.id %}"class="btn btn-danger col-md-5">Delete</a>
        <button class="btn btn-success col-md-5 offset-md-1">{{ action }} Quiz</button>
        {% else %}
        <button class="btn btn-success btn-block">{{ action }} Quiz</button>
        {% endif %}
    </form>
</div>
{% endblock %}

quizapp/quizzes/templates/quizzes/quiz_created_detail.html
{% extends 'base.html' %}

{% block head %}
<title>Quiz Application | Home</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">List of Questions</h1>
    <h3 class="text-center">
        Quiz: {{ quiz.title }} <a href="{% url 'quizzes:quiz_update' quiz.id %}" class="fas fa-edit text-primary"></a>
    </h3>

    <hr>
    <div class="col-md-4 offset-md-4 text-center">
        <a href="{% url 'quizzes:question_create' quiz.id%}" class="btn btn-outline-primary">Add a question</a>
    </div>
    <br>
    {% if quiz.question_set.all %}
    {% for question in quiz.question_set.all %}
    <div class="row">
        <div class="col-md-4 offset-md-4 text-center">
        <h4 class="text-center text-info" style="display;">
            {{ question.question_text }} <a href="{% url 'quizzes:question_update' question.id%}"><span class="fas fa-edit text-primary"></span></a>
            <div class="col-md-4 offset-md-4 text-center">
                <a href="{% url 'quizzes:choice_create' question.id %}" class="btn btn-sm btn-outline-primary text-center">
                    Choice <i class="fas fa-plus"></i>
                </a>
            </div>
        </h4>

        <table class="table table-responsive">
            <tbody>
                {% for choice in question.choice_set.all %}
                <td {% if choice.is_correct %} class="table-success" {% endif %}>
                    <a href="{% url 'quizzes:choice_update' choice.id %}">
                        <i class="fas fa-edit"></i>
                    </a>
                    <p>{{ choice }}</p>
                </td>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h4 class="text-center">No questions created</h4>
    {% endif %}
    {% include 'pagination.html' %}
</div>
{% endblock %}

quizapp/quizzes/templates/quizzes/quiz_created_index.html
{% extends 'base.html' %}

{% block head %}
<title>Quiz Application | Home</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">List of Quizzes</h1>
    <hr>
    <div class="col-md-4 offset-md-4 text-center">
        <a href="{% url 'quizzes:create' %}" class="btn btn-outline-primary">Create a quiz here</a>
    </div>
    <br>
    {% if quiz_list %}
    <table class="table table-hover text-center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Quiz Name</th>
                <th scope="col">Date Created</th>
                <th scope="col">Expiration Date</th>
                <th scope="col">Published</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in quiz_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'quizzes:usercreated_detail' quiz.id %}">{{ quiz.title }}</a></td>
                <td>{{ quiz.date_created|date:'F d, Y' }}</td>
                <td>{{ quiz.expiration_date|date:'F d, Y' }}</td>
                <td>
                    {% if quiz.published %}
                    <i class="fas fa-check-circle text-success"></i>
                    {% else %}
                    <i class="fas fa-times-circle text-danger"></i>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h4 class="text-center">No quizzes Created</h4>
    {% endif %}
    {% include 'pagination.html' %}
</div>
{% endblock %}